repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-q", "-r", ".", "-x", ".venv,chronograf-1.8.6-1"]
        language_version: python3
        env:
          PYTHONIOENCODING: "utf-8"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--ignore-missing-imports"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        args: ["protect", "--no-banner", "--report-format", "json"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov --maxfail=1
        language: system
        types: [python]
        pass_filenames: false
      - id: trivy
        name: trivy fs
        entry: trivy fs --quiet --exit-code 1 --skip-dirs .venv --skip-dirs chronograf-1.8.6-1 .
        language: system
        pass_filenames: false
default_stages:
  - pre-commit
  - pre-push
