apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: internetspeed
    user: speedmonitor
    isDefault: true
    basicAuth: false
    jsonData:
      httpMode: GET
      version: InfluxQL
    secureJsonData:
      password: speedmonitor
